/** What changed, version by version (newest first). Each note: at most 50 words. */
export const PATCH_NOTES: { v: string; note: string }[] = [
  { v: '0.82.1', note: 'Slimmer gauges: the stamina bars and the pass and shot power bar are thinner, with a fine black outline, and fill from red to green. The shot bar turns red again past full power, where it would fly over.' },
  { v: '0.82', note: 'Tackles reworked. Once you commit, you go where your momentum takes you: no more snapping round after the ball. Slides bend only slightly at a sprint, last longer on the grass, and the leg reaches for the ball. The ball now flies off the leg how it was struck.' },
  { v: '0.81.2', note: 'Crosses show their aim: hold Pass and slide up on the ball out wide, and the gold ring and the ball’s flight appear where the cross will come down. The stick steers which runner it’s for, and the ring follows.' },
  { v: '0.81.1', note: 'The goal roar no longer audibly ends and restarts: after the first take, three overlapping, staggered copies of it swell in underneath, each drifting in level, carrying the roar seamlessly through the celebration.' },
  { v: '0.81', note: 'Sprint or press on a high ball and your player attacks it: real aerial duels, decided by jump, height, strength and run-up, with the winner heading it under pressure. Pressing the carrier now moves with him instead of trailing, sprint gets right up against him, and any loose touch gets pounced on.' },
  { v: '0.80.5', note: 'Rain is half as loud.' },
  { v: '0.80.4', note: 'Fixed the fans’ flags in the stands shaking faster and faster the longer you played until they flickered. Their ripple now speeds up mid-swing and settles at the turn, at the same gentle pace all match.' },
  { v: '0.80.3', note: 'No more sparkle on the grass late in the match: the dew no longer throws twinkling floodlight glints across the pitch. The soft evening sheen on the turf stays.' },
  { v: '0.80.2', note: 'The buttons say what they do while you line up a corner (Whip, Short, Float) or a goal kick (Drive, Short, Float), and go back to Pass, Through and Shoot once the ball is struck.' },
  { v: '0.80.1', note: 'Penalties are deafening: from the whistle, through the walk-up and the run-up, until the kick has gone in, been saved or gone wide, the whole crowd is at full cry.' },
  { v: '0.80', note: 'The stick steers your player’s chase for a loose ball much more: up to 70% of the run (was 45%), and about 35% even when the ball is tight to win. Leave the stick alone and he simply goes and meets it.' },
  { v: '0.79', note: 'Club studio: Tifos is now its own tab next to Crest, with the stand banner. Save look keeps your name, code, kit, crest, banner and tifo pictures; try Surprise me as much as you like, then Back to saved brings it all back.' },
  { v: '0.78', note: 'New Tifos page in Club settings (the gear on the Club screen): upload your own picture for the giant hanging tifo, the home end card display and the fan banner, or go back to the club design. The fan banner upload moved here from the pause menu.' },
  { v: '0.77.3', note: 'The goal roar now lasts the whole celebration and the crowd shot, the recording blending into itself, and only starts to fade as the camera brings the players back for the restart.' },
  { v: '0.77.2', note: 'A much bigger crowd surge near goal: it now starts building 12 m from the goal line (was 5 m) and climbs exponentially to about seven times as loud on the line (was three), with a limiter so it never distorts.' },
  { v: '0.77.1', note: 'Fixed the club studio on phones: the club name box no longer pushes the three-letter code off the edge, so you can tap the code and edit it again. The code box is a little wider too.' },
  { v: '0.77', note: 'Walk-out before kick-off: the teams come out of a new tunnel, wide shots of the ground end on a giant home tifo dropped from the main stand roof, then the captains meet the referees. Tap to skip each shot. Pick your captain on the Squad screen; both captains wear armbands.' },
  { v: '0.76.3', note: 'The goal roar starts straight away: the recording now skips its first tenth of a second.' },
  { v: '0.76.2', note: 'Fixed the stamina card in matches: it showed up huge, upright and mid-screen because it shared a name with the collectible player cards. It now sits small in the bottom-left corner, and the collectible cards look right again too.' },
  { v: '0.76.1', note: 'No more trumpets: the crowd no longer sings with synthesised voices, which sounded like brass, and the rising "ooo" in attacks is gone. The drum, claps, Viking HUH, boos, near-miss ooh and the groan after a goal stay, now as breathy shouts.' },
  { v: '0.76', note: 'Livelier keepers: the ready stance eases in and out, shifts its weight and keeps the hands moving. Dives stretch with soft elbows and a tucked top leg, land curled, gather a held ball, push up off the grass. High catches raise a knee; low ones go down on one knee.' },
  { v: '0.75', note: 'A real crowd: the stadium noise is now a recording, five overlapping copies drifting up and down so it never loops audibly. It swells with danger and surges steeply in the last few metres before the goal line. Goals bring a recorded roar. Chants, drums and claps stay.' },
  { v: '0.74', note: 'Your stick counts for more when your player goes for a loose ball: it bends his run up to 45% (was 30%), and still leans it a little even when the ball is tight to win.' },
  { v: '0.73', note: 'Stamina you can feel and see: a tired player loses up to a quarter of his top speed and nearly a third of his acceleration. Bottom left shows your player’s name and stamina, boxed green for defenders, yellow for midfielders, red for attackers, with a thin bar over his head.' },
  { v: '0.72', note: 'Running arms like a real player: they swing a beat behind the legs, further forward than back. On the forward swing the elbow closes and the hand comes up across the chest; on the back swing the arm opens and tucks by the hip. Walking arms hang looser.' },
  { v: '0.71.1', note: 'Softer goal nets: a shot now bulges the net out deeper and wider, and it takes longer to settle, with a slower, looser ripple. Gentler finishes move it more than before too.' },
  { v: '0.71', note: 'Turns that flow: players look into a new direction first, hips lead the shoulders round and feet point into the turn. Cutting at speed they sink, fold the inside knee, push the outside leg wide and lean the trunk in; arms swing out to balance.' },
  { v: '0.70', note: 'Aimed goal kicks, like corners: a gold ring and the ball’s flight on the grass. Steer the ring anywhere upfield, then Pass drives it there low and quick, Shoot floats it high, and Through rolls it short to the nearest team-mate. Your nearest player runs to meet it.' },
  { v: '0.69.1', note: 'The referee no longer blows for half time or full time in the middle of an attack. Once the added time is up he lets it play out, and blows when the ball leaves the final third, the defenders win it, the keeper catches it or it goes dead.' },
  { v: '0.69', note: 'Choose your ground before every kick-off: the big stadium, the Old Ground, or a new bare pitch with nothing around it (no stands, crowd, pylons or dugouts, and no chants), to see what the scenery costs your frame rate. The ground setting moved out of Club, Kit.' },
  { v: '0.68', note: 'Big performance pass: players out of view cost nothing, cheaper pitch, crowd and particle drawing, quieter audio when silent, menus no longer run the stadium behind them, and the match engine thinks about a quarter faster with identical results. Phones that can’t hold 120 fps settle at a smooth 60.' },
  { v: '0.67', note: 'Living benches: seven real substitutes in each dugout, in team kit with their own bodies. Mostly sat, each his own way, they get up to stretch, walk out to watch, squat at the line, warm up, lean in for chances, clutch heads at misses and leap up for goals.' },
  { v: '0.66', note: 'Livelier players: arms and heads swing with speed-ups, stops and turns, shoulders and neck move, and feet plant on the grass, rolling heel to toe instead of sliding. Catches, carries and throw-ins no longer reach behind the back; instep strikes point the toes.' },
  { v: '0.65', note: 'Your aim counts: a pass goes to a team-mate within about 40° of where the stick points, a through ball too, now also played along the stick’s own line. Nobody there? It goes into the space you aimed at, never off the other way.' },
  { v: '0.64', note: 'Offside is called. Strayed beyond the last defender when a teammate plays it, then touch the ball, and the linesman’s flag goes up: indirect free kick to the defenders. Not from throw-ins, corners or goal kicks. The computer’s forwards hold their runs and leave the ball when caught.' },
  { v: '0.63.1', note: 'New loading screen in the game’s pixel art: it opens on the app icon, exactly where the phone’s launch screen leaves it, then the floodlights flicker on, the stand lights up and a pixel ball rolls along a block-by-block loading bar.' },
  { v: '0.63', note: 'Stoppage time: each half now runs on for 1 to 5 added minutes. The board goes up at 45 and 90 minutes (+3 beside the clock) and the clock carries on, 45+1, 45+2, until the whistle.' },
  { v: '0.62.1', note: 'Smaller pause menu: compact buttons and text. No more instruction banners during corners, free kicks, penalties, goal kicks, throw-ins and kick-offs.' },
  { v: '0.62', note: 'Through balls reworked: struck at the right pace into the space a runner reaches first, so most now find him in stride. Players judge loose balls by who gets there first and meet them sooner. Strikers time runs off the passer having time to look up.' },
  { v: '0.61', note: 'A new home ground: the Old Ground, a second-division classic. Four separate stands, lattice floodlight pylons in the open corners, a covered Shed for the home end, an away cage, terraced houses and a church spire beyond. Pick it under Club, Kit, Home ground.' },
  { v: '0.60.2', note: 'The score card after a goal now pops up in the middle of the screen.' },
  { v: '0.60', note: 'Goal kicks seen from behind the keeper, like free kicks. The other side’s goal kicks, direct free kicks and penalties too: the camera drops in behind their taker as he lines up.' },
  { v: '0.59', note: 'Five body types — lean, athletic, muscular, stocky, tall & lanky — read from each player’s height, weight and strength. Proportions, limb thickness and length now differ; everyone still stands at his real height. Shown in the squad.' },
  { v: '0.58', note: 'A 90s game-night look for the menus: pixel type, square pixel-cornered panels with hard shadows, banded colours and CRT scanlines.' },
  { v: '0.57', note: 'Celebrate your goals: after scoring, the four buttons pick the move. Knee slide, aeroplane, the SIUU leap and a backflip.' },
  { v: '0.56', note: 'The crowd peaks when your team has the ball within 20 m of goal: at least half its roar, full roar when the player is running at goal, fast. Patch notes on the home screen.' },
  { v: '0.55', note: 'Corner camera frames the whole box and goal, taker at the edge. In attack the camera leans toward the goal. Rainy nights a little gentler, fewer puddles.' },
  { v: '0.54', note: 'The crowd builds as the ball nears goal and erupts on goals; groans for near misses. Songs suit the score. Confetti showers that stay on the pitch for a while.' },
  { v: '0.53', note: 'Lighter terraces effects. Frame rate: 120 in play, 90 on the home screen, 60 in the pause menu. Smaller minimap, hidden while paused.' },
  { v: '0.52', note: 'European nights: chants, drums, claps and the Viking clap; flares and smoke bombs lighting the ends; boos; tifos in both ends. FIFA-style corners with a landing ring and flight arc.' },
  { v: '0.51', note: 'Players turn and stop a little quicker. Defenders lunge to cut out passes.' },
  { v: '0.50', note: 'A minimap at the bottom of the screen. Edit your club’s 3-letter code.' },
  { v: '0.48', note: 'A burst of pace for a ball that’s right there, and a leg stretched out to reach it. Fine Pixels slider.' },
  { v: '0.47', note: '120 fps cap. Smoothing on/off in the pause menu.' },
  { v: '0.46', note: 'Players run facing where they’re going and turn their heads to watch the ball. Graphics optimisation.' },
  { v: '0.45', note: 'Crisper pixel art with a Pixels slider. Players step across a passing ball at full pace.' },
  { v: '0.44', note: 'Passing and receiving rebuilt on how players really run: passes timed to arrive with the runner, receivers that don’t overrun the ball, through balls that die into the runner’s path.' },
  { v: '0.43', note: 'Rainy night weather. A 2.5D crowd that stands up off the terraces. The stick steers your run a little more.' },
  { v: '0.42', note: 'Slide tackles leave dirt marks on the pitch.' },
  { v: '0.41', note: 'Goal celebrations filmed from the front: the scorer’s roar and signature pose.' },
  { v: '0.40', note: 'The stand behind the camera appears for free kicks and penalties.' },
  { v: '0.39', note: 'Players reach and stretch naturally for the ball; slide tackles shaped by the slide itself.' },
  { v: '0.38', note: 'First-time shots that take the ball as it comes: volleys, half-volleys, one-timers.' },
  { v: '0.37', note: 'Ball seeking: the earliest point on the ball’s path you can reach.' },
  { v: '0.36', note: 'Tackled players go down from the force of the hit.' },
  { v: '0.33', note: 'Keepers play back-passes with their feet. Team-mates step out of the way of a kick.' },
  { v: '0.32', note: 'Switching player cancels a loaded pass or shot. The stadium keeps full detail at any distance.' },
  { v: '0.31', note: 'Colour-graded power gauge for free kicks and penalties. Pixel art is the graphics look. FPS counter setting.' },
  { v: '0.30', note: 'Fouls only on real contact; better keeper reach; shots pass team-mates; new tackle animations.' },
  { v: '0.29', note: 'The stadium rebuilt as an old English ground.' },
  { v: '0.27', note: 'Charge bar over the aiming reticle on free kicks and penalties. Faster pack openings.' },
  { v: '0.25', note: 'Warmer, brighter light. Write the home end’s drop banner.' },
  { v: '0.22', note: 'Third-person free kicks and penalties. Club studio: kit designer and crest maker.' },
  { v: '0.17', note: 'Fouls, cards, advantage, free kicks with walls, and penalties.' },
  { v: '0.13', note: 'Home screen, squad builder, player stats and the pack store. A two-tier stadium with an ultras end.' },
];
