/** What changed, version by version (newest first). Each note: at most 50 words. */
export const PATCH_NOTES: { v: string; note: string }[] = [
  { v: '0.61', note: 'Through balls reworked: struck at the right pace into the space a runner reaches first, so most now find him in stride. Players judge loose balls by who gets there first and meet them sooner. Strikers time runs off the passer having time to look up.' },
  { v: '0.60', note: 'Goal kicks seen from behind the keeper, like free kicks. The other side’s goal kicks, direct free kicks and penalties too: the camera drops in behind their taker as he lines up.' },
  { v: '0.59', note: 'Five body types — lean, athletic, muscular, stocky, tall & lanky — read from each player’s height, weight and strength. Proportions, limb thickness and length now differ; everyone still stands at his real height. Shown in the squad.' },
  { v: '0.58', note: 'A 90s game-night look for the menus: pixel type, square pixel-cornered panels with hard shadows, banded colours and CRT scanlines.' },
  { v: '0.57', note: 'Celebrate your goals: after scoring, the four buttons pick the move. Knee slide, aeroplane, the SIUU leap and a backflip.' },
  { v: '0.56', note: 'The crowd peaks when your team has the ball within 20 m of goal: at least half its roar, full roar when the player is running at goal, fast. Patch notes on the home screen.' },
  { v: '0.55', note: 'Corner camera frames the whole box and goal, taker at the edge. In attack the camera leans toward the goal. Rainy nights a little gentler, fewer puddles.' },
  { v: '0.54', note: 'The crowd builds as the ball nears goal and erupts on goals; groans for near misses. Songs suit the score. Confetti showers that stay on the pitch for a while.' },
  { v: '0.53', note: 'Lighter terraces effects. Frame rate: 120 in play, 90 on the home screen, 60 in the pause menu. Smaller minimap, hidden while paused.' },
  { v: '0.52', note: 'European nights: chants, drums, claps and the Viking clap; flares and smoke bombs lighting the ends; boos; tifos in both ends. FIFA-style corners with a landing ring and flight arc.' },
  { v: '0.51', note: 'Players turn and stop a little quicker. Defenders lunge to cut out passes.' },
  { v: '0.50', note: 'A minimap at the bottom of the screen. Edit your club’s 3-letter code.' },
  { v: '0.48', note: 'A burst of pace for a ball that’s right there, and a leg stretched out to reach it. Fine Pixels slider.' },
  { v: '0.47', note: '120 fps cap. Smoothing on/off in the pause menu.' },
  { v: '0.46', note: 'Players run facing where they’re going and turn their heads to watch the ball. Graphics optimisation.' },
  { v: '0.45', note: 'Crisper pixel art with a Pixels slider. Players step across a passing ball at full pace.' },
  { v: '0.44', note: 'Passing and receiving rebuilt on how players really run: passes timed to arrive with the runner, receivers that don’t overrun the ball, through balls that die into the runner’s path.' },
  { v: '0.43', note: 'Rainy night weather. A 2.5D crowd that stands up off the terraces. The stick steers your run a little more.' },
  { v: '0.42', note: 'Slide tackles leave dirt marks on the pitch.' },
  { v: '0.41', note: 'Goal celebrations filmed from the front: the scorer’s roar and signature pose.' },
  { v: '0.40', note: 'The stand behind the camera appears for free kicks and penalties.' },
  { v: '0.39', note: 'Players reach and stretch naturally for the ball; slide tackles shaped by the slide itself.' },
  { v: '0.38', note: 'First-time shots that take the ball as it comes: volleys, half-volleys, one-timers.' },
  { v: '0.37', note: 'Ball seeking: the earliest point on the ball’s path you can reach.' },
  { v: '0.36', note: 'Tackled players go down from the force of the hit.' },
  { v: '0.33', note: 'Keepers play back-passes with their feet. Team-mates step out of the way of a kick.' },
  { v: '0.32', note: 'Switching player cancels a loaded pass or shot. The stadium keeps full detail at any distance.' },
  { v: '0.31', note: 'Colour-graded power gauge for free kicks and penalties. Pixel art is the graphics look. FPS counter setting.' },
  { v: '0.30', note: 'Fouls only on real contact; better keeper reach; shots pass team-mates; new tackle animations.' },
  { v: '0.29', note: 'The stadium rebuilt as an old English ground.' },
  { v: '0.27', note: 'Charge bar over the aiming reticle on free kicks and penalties. Faster pack openings.' },
  { v: '0.25', note: 'Warmer, brighter light. Write the home end’s drop banner.' },
  { v: '0.22', note: 'Third-person free kicks and penalties. Club studio: kit designer and crest maker.' },
  { v: '0.17', note: 'Fouls, cards, advantage, free kicks with walls, and penalties.' },
  { v: '0.13', note: 'Home screen, squad builder, player stats and the pack store. A two-tier stadium with an ultras end.' },
];
